#!/usr/bin/env bash
# init-context.sh — Initialize the docs/ context directory in a project
#
# Usage: bash scripts/init-context.sh [target-dir]
#   target-dir: path to the project root (default: current directory)
#
# Example: bash scripts/init-context.sh /path/to/my-project

set -euo pipefail

TARGET="${1:-.}"

if [ ! -d "$TARGET" ]; then
  echo "Error: target directory '$TARGET' does not exist."
  exit 1
fi

CTX="$TARGET/docs"

echo "Initializing agentic-sdlc context directory at: $CTX"

mkdir -p "$CTX/architecture/adrs"
mkdir -p "$CTX/architecture/rfcs"
mkdir -p "$CTX/product/features"
mkdir -p "$CTX/investigations/spikes"
mkdir -p "$CTX/sdlc/epics"
mkdir -p "$CTX/sdlc/stories"
mkdir -p "$CTX/sdlc/workspaces"
mkdir -p "$CTX/sdlc/test-plans"
mkdir -p "$CTX/sdlc/retrospectives"

# Create stub files with minimal frontmatter
create_stub() {
  local file="$1"
  local title="$2"
  local stage="$3"
  if [ ! -f "$file" ]; then
    cat > "$file" << EOF
# $title

> **Status:** Not started
> **Stage:** $stage
> **Last updated:** \$(date +%Y-%m-%d)

_This file is generated by the agentic-sdlc framework._
_Populate it by following the $stage skill._
EOF
    echo "  Created: $file"
  else
    echo "  Skipped (exists): $file"
  fi
}

create_stub "$CTX/architecture/domain-model.md"        "Domain Knowledge"         "inception"
create_stub "$CTX/product/features/brd.md"             "Business Requirements"    "inception"
create_stub "$CTX/product/design-system.md"            "Design System"            "design-system"
create_stub "$CTX/product/personas.md"                 "Personas"                 "inception"
create_stub "$CTX/architecture/tech-architecture.md"   "Technical Architecture"   "tech-architecture"
create_stub "$CTX/architecture/coding-standards.md"    "Coding Constitution"      "tech-architecture"
create_stub "$CTX/sdlc/epics/implementation-plan.md"   "Implementation Plan"      "implementation-planning"
create_stub "$CTX/architecture/data-domain.md"         "Interface Contracts"      "implementation-planning"
create_stub "$CTX/product/accessibility.md"            "Accessibility Requirements" "design-system"

# Brownfield only
create_stub "$CTX/architecture/existing-system.md"     "Existing System Analysis" "context-harvest"

# Create a .gitkeep in empty directories so git tracks them
touch "$CTX/architecture/adrs/.gitkeep"
touch "$CTX/architecture/rfcs/.gitkeep"
touch "$CTX/investigations/spikes/.gitkeep"
touch "$CTX/sdlc/stories/.gitkeep"
touch "$CTX/sdlc/workspaces/.gitkeep"
touch "$CTX/sdlc/test-plans/.gitkeep"
touch "$CTX/sdlc/retrospectives/.gitkeep"
echo "  Created .gitkeep tracking files in new domains."

echo ""
echo "Done! Context directory ready at: $CTX"
echo ""
echo "Next steps:"
echo "  Greenfield: Read skills/using-agentic-sdlc/SKILL.md, then skills/inception/SKILL.md"
echo "  Brownfield: Read skills/using-agentic-sdlc/SKILL.md, then skills/context-harvest/SKILL.md"
