import json
import os
import shutil
import sys
import click
from pathlib import Path
from datetime import datetime
from . import dashboard
from .eval import validator as skill_validator
from .eval import harness as skill_harness

@click.group()
def main():
    """Agentic SDLC CLI - Multi-stage software development lifecycle for AI agents."""
    pass

@main.command()
@click.argument('target', default='.', type=click.Path(exists=True, file_okay=False, dir_okay=True))
@click.option('--force', is_flag=True, help="Overwrite existing files.")
def init(target, force):
    """Initialize the Agentic SDLC structure in a target project."""
    target_path = Path(target).resolve()
    click.echo(f"Initializing Agentic SDLC in {target_path}...")

    # 1. Create directory structure
    dirs = [
        "docs/architecture/adrs",
        "docs/architecture/rfcs",
        "docs/product/features",
        "docs/investigations/spikes",
        "docs/sdlc/epics",
        "docs/sdlc/stories",
        "docs/sdlc/workspaces",
        "docs/sdlc/test-plans",
        "docs/sdlc/retrospectives",
    ]
    for d in dirs:
        (target_path / d).mkdir(parents=True, exist_ok=True)
        # Create .gitkeep
        (target_path / d / ".gitkeep").touch()

    # 2. Create stub files
    stubs = [
        ("docs/architecture/domain-model.md", "Domain Knowledge", "inception"),
        ("docs/product/features/brd.md", "Business Requirements", "inception"),
        ("docs/product/design-system.md", "Design System", "design-system"),
        ("docs/product/personas.md", "Personas", "inception"),
        ("docs/architecture/tech-architecture.md", "Technical Architecture", "tech-architecture"),
        ("docs/architecture/coding-standards.md", "Coding Constitution", "tech-architecture"),
        ("docs/sdlc/epics/implementation-plan.md", "Implementation Plan", "implementation-planning"),
        ("docs/architecture/data-domain.md", "Interface Contracts", "implementation-planning"),
        ("docs/product/accessibility.md", "Accessibility Requirements", "design-system"),
        ("docs/architecture/existing-system.md", "Existing System Analysis", "context-harvest"),
    ]

    for file_rel, title, stage in stubs:
        file_path = target_path / file_rel
        if not file_path.exists() or force:
            with open(file_path, 'w') as f:
                f.write(f"# {title}\n\n")
                f.write(f"> **Status:** Not started\n")
                f.write(f"> **Stage:** {stage}\n")
                f.write(f"> **Version:** 0.1.0\n")
                f.write(f"> **Last updated:** {datetime.now().strftime('%Y-%m-%d')}\n\n")
                f.write(f"_This file is generated by the agentic-sdlc framework._\n")
                f.write(f"_Populate it by following the {stage} skill._\n")
            click.echo(f"  Created {file_rel}")

    # 3. Copy skills, templates, and core files from package
    package_root = Path(__file__).parent
    
    # Copy skills
    if (target_path / "skills").exists() and not force:
        click.echo("  Skill directory already exists. Use --force to overwrite.")
    else:
        if (target_path / "skills").exists():
            shutil.rmtree(target_path / "skills")
        shutil.copytree(package_root / "skills", target_path / "skills")
        click.echo("  Copied skills directory.")

    # Copy templates
    if (target_path / "templates").exists() and not force:
        click.echo("  Templates directory already exists. Use --force to overwrite.")
    else:
        if (target_path / "templates").exists():
            shutil.rmtree(target_path / "templates")
        shutil.copytree(package_root / "templates", target_path / "templates")
        click.echo("  Copied templates directory.")

    # Copy fixtures
    if (target_path / "fixtures").exists() and not force:
        click.echo("  Fixtures directory already exists. Use --force to overwrite.")
    else:
        if (target_path / "fixtures").exists():
            shutil.rmtree(target_path / "fixtures")
        if (package_root / "fixtures").exists():
            shutil.copytree(package_root / "fixtures", target_path / "fixtures")
            click.echo("  Copied fixtures directory.")

    # Copy core files (AGENTS.md, etc.)
    for core_file in (package_root / "core").glob("*.md"):
        dest = target_path / core_file.name
        if not dest.exists() or force:
            shutil.copy(core_file, dest)
            click.echo(f"  Copied {core_file.name}")

    click.echo("\nDone! Agentic SDLC is ready.")
    click.echo("Next steps:")
    click.echo("  1. Instruct your agent: 'Read AGENTS.md and skills/using-agentic-sdlc/SKILL.md'")
    click.echo("  2. Start with 'inception' (greenfield) or 'context-harvest' (brownfield)")

@main.command()
@click.argument('project_root', default='.')
@click.option('--port', default=8080, help="Port to serve the dashboard on.")
def serve(project_root, port):
    """Start the Agnetic SDLC dashboard."""
    dashboard.serve(project_root, port)


@main.command('validate-skills')
@click.argument('repo_root', default='.', type=click.Path(exists=True, file_okay=False, dir_okay=True))
@click.option('--json-output', 'json_output', is_flag=True, default=False,
              help='Emit results as JSON instead of human-readable text.')
def validate_skills(repo_root, json_output):
    """Validate all SKILL.md files for structural correctness and consistency."""
    root = Path(repo_root).resolve()
    report = skill_validator.validate(root)

    if json_output:
        click.echo(json.dumps(report.as_dict(), indent=2))
    else:
        status = "PASS" if report.ok else "FAIL"
        click.echo(f"validate-skills: {status} ({report.checks_run} checks, "
                   f"{len(report.errors)} errors, {len(report.warnings)} warnings)")
        for issue in report.errors:
            loc = f":{issue.line}" if issue.line else ""
            click.echo(f"  ERROR  [{issue.rule_id}] {issue.path}{loc} — {issue.message}")
        for issue in report.warnings:
            loc = f":{issue.line}" if issue.line else ""
            click.echo(f"  WARN   [{issue.rule_id}] {issue.path}{loc} — {issue.message}")

    sys.exit(0 if report.ok else 1)


@main.command('eval-skills')
@click.argument('repo_root', default='.', type=click.Path(exists=True, file_okay=False, dir_okay=True))
@click.option('--skill', default=None, help='Only eval fixtures for this skill name.')
@click.option('--fixtures', 'fixtures_dir', default=None,
              help='Path to fixtures directory. Defaults to <repo_root>/fixtures.')
@click.option('--json-output', 'json_output', is_flag=True, default=False,
              help='Emit results as JSON instead of human-readable text.')
def eval_skills(repo_root, skill, fixtures_dir, json_output):
    """Run deterministic scenario fixtures against selected skills."""
    root = Path(repo_root).resolve()
    fixtures_root = Path(fixtures_dir).resolve() if fixtures_dir else root / 'fixtures'

    if not fixtures_root.exists():
        package_fixtures = Path(__file__).parent / 'fixtures'
        if package_fixtures.exists():
            fixtures_root = package_fixtures

    if not fixtures_root.exists():
        click.echo(f"eval-skills: fixtures directory not found: {fixtures_root}", err=True)
        sys.exit(1)

    report = skill_harness.run(root, fixtures_root, skill_filter=skill)

    if json_output:
        click.echo(json.dumps(report.as_dict(), indent=2))
    else:
        status = "PASS" if report.ok else "FAIL"
        click.echo(f"eval-skills: {status} ({report.scenarios_run} scenarios, "
                   f"{report.passed} passed, {report.failed} failed)")
        for result in report.results:
            if not result.ok:
                click.echo(f"  FAIL [{result.scenario_id}] skill={result.skill}")
                for failure in result.failures:
                    click.echo(f"       - {failure}")

    sys.exit(0 if report.ok else 1)


if __name__ == "__main__":
    main()
